### ISSUE TITLE
java.util.NoSuchElementException: null when update dependencies

### ISSUE THREAD

**Issue by Zeon8** [consulo/consulo-nuget#2]
I have packages.config:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.ClearScript" version="7.1.1" targetFramework="net46" />
</packages>
```
And when I update dependencies I get an this in consulo.log file:
```
java.util.NoSuchElementException: null
	at java.util.StringTokenizer.nextToken(StringTokenizer.java:349) ~[?:?]
	at consulo.nuget.api.NuGetPackageEntryParser.parse(NuGetPackageEntryParser.java:79) ~[?:?]
	at consulo.nuget.module.extension.NuGetBasedRepositoryWorker$3.process(NuGetBasedRepositoryWorker.java:447) ~[?:?]
	at consulo.nuget.module.extension.NuGetBasedRepositoryWorker$3.process(NuGetBasedRepositoryWorker.java:436) ~[?:?]
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:405) ~[JnaLoader.class:?]
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:387) ~[JnaLoader.class:?]
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:251) ~[JnaLoader.class:?]
	at consulo.nuget.module.extension.NuGetRequestQueue.request(NuGetRequestQueue.java:49) ~[?:?]
	at consulo.nuget.module.extension.NuGetBasedRepositoryWorker.requestPackageEntries(NuGetBasedRepositoryWorker.java:434) ~[?:?]
	at consulo.nuget.module.extension.NuGetBasedRepositoryWorker.resolvePackageEntry(NuGetBasedRepositoryWorker.java:410) ~[?:?]
	at consulo.nuget.module.extension.NuGetBasedRepositoryWorker$2.run(NuGetBasedRepositoryWorker.java:218) ~[?:?]
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:895) ~[PluginManagerCore.class:?]
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:180) ~[PluginManagerCore.class:?]
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:592) ~[PluginManagerCore.class:?]
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:539) ~[PluginManagerCore.class:?]
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63) ~[ApplicationStarter.class:?]
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:167) ~[PluginManagerCore.class:?]
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.lambda$run$0(CoreProgressManager.java:413) ~[PluginManagerCore.class:?]
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:222) [StringUtil.class:?]
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:413) [PluginManagerCore.class:?]
	at consulo.application.impl.RunnableAsCallable.call(RunnableAsCallable.java:33) [ApplicationStarter.class:?]
	at consulo.application.impl.RunnableAsCallable.call(RunnableAsCallable.java:24) [ApplicationStarter.class:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[  51861]  ERROR - ion.NuGetBasedRepositoryWorker - Consulo 2021.4  Build #2877 
[  51861]  ERROR - ion.NuGetBasedRepositoryWorker - JDK: 11.0.9.1 
[  51861]  ERROR - ion.NuGetBasedRepositoryWorker - VM: OpenJDK 64-Bit Client VM 
[  51862]  ERROR - ion.NuGetBasedRepositoryWorker - Vendor: AdoptOpenJDK 
[  51862]  ERROR - ion.NuGetBasedRepositoryWorker - OS: Windows 10 
```

**Comment by VISTALL** [comment]
Hello. I will check in near future. thanks

**Comment by VISTALL** [comment]
I can't this problem. It's new nuget dependencies. But after fix I catch new error, like old api v2, have limits and it's not resolved dependencies correctly.

Need rewrite to v3, but it will be not fast.
